sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.5"

before_install:
  - pip3 install cwltool
  - docker build -t Corekaburra .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /Corekaburra/.travis/unit-test.sh Corekaburra
  # Unit tests
  - docker run --entrypoint /Corekaburra/functional_tests/Corekaburra-test.sh Corekaburra -p Corekaburra -d /Corekaburra/functional_tests/test_data -v

  # CWL definition test
  - cwltool Corekaburra.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
