name: 'Corekaburra_test_suite'
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build Docker image'
        run: docker build -t corekaburra .
      - name: 'Run unit tests'
        run: docker run --entrypoint /Corekaburra/.travis/unit-test.sh corekaburra
      - name: 'Run functional tests'
        run: docker run --entrypoint /Corekaburra/functional_tests/Corekaburra-test.sh corekaburra -p Corekaburra -d /Corekaburra/functional_tests/test_data -v
